### ISSUE TITLE
searchTwitter error with since/until arguments

### ISSUE THREAD

**Issue by geotheory** [geoffjentry/twitteR#82]
I'm getting errors when I try to implement the date constraints since and until.  For instance:

`searchTwitter("stuff", n=5, since="2014-02-01", until="2015-02-15")
Warning message:
In doRppAPICall("search/tweets", n, params = params, retryOnRateLimit = retryOnRateLimit,  :
  5 tweets were requested but the API can only return 0`

Any idea why?

**Comment by geoffjentry** [comment]
You can't search back more than a couple of days, as per the API. The error message is telling you exactly why, you've requested 5 and the API is only returning 0.

**Comment by Horopter** [comment]
Mr. Gentry,  hi
My project heavily depends on collecting yearwise data from twitter feed. If since and until touch only few days back, I'll lose a great deal of my project. Kindly provide provision to access data from 2010 to 2016 please.

**Comment by EspenRemman** [comment]
The history constraint is placed by Twitter , not  by geoffjentry and the twitteR package.

**Comment by mahnoor777** [comment]
I want to research on the topic of election those were held in USA. I want tweets for 16th march,2016 and 17th march,2016 (only for two days) for both Hillary Clinton and Donald Trump. But get error.
I am a needy student. I can't afford the Twitter's premium access to API to get the historical tweets and other websites those are charging. My University is also not funding me in my research. Tell me the way free of cost so that I can complete my research.  Kindly help me in this regard. That will be very helpful for me. Thanks
